### ISSUE TITLE
Lint is incorrect for constructor : Inferno Error: cannot update state via setState() in constructor. Instead, assign to `this.state` directly or define a `state = {};`

### ISSUE THREAD

**Issue by dessalines** [infernojs/eslint-plugin-inferno#15] opened 2022-08-02 12:49 UTC
If I use `state = ...` in a constructor, it fails lint. If I follow lint and use `setState(`, I get the following error:

404: Error: Inferno Error: cannot update state via setState() in constructor. Instead, assign to `this.state` directly or define a `state = {};`

**Comment by Havunen** [comment] 2022-08-02 13:51
> If I use state = ... in a constructor, it fails lint.

Which linting rule are using? I recommend https://github.com/infernojs/eslint-plugin-inferno for inferno apps.

I think the linter is trying to say that it might cause unexpected behavior if you assign state directly. Because then any derived class by assigning the state in constructor would override the assigned value done in base class. 

This is expected behavior in Inferno and in React too.

One option is to set the properties to state in constructor:

```jsx
class MyComponent extends Component {
  constructor(props) {
    super(props)
    this.state.counter = 0;
  }
}

```

or by using object assign

```jsx
class MyComponent extends Component {
  constructor(props) {
    super(props)
    
    Object.assign(this.state, {
        counter: 0
    });
  }
}

```

**Comment by dessalines** [comment] 2022-08-02 14:05
`this.state.counter = 0;`

This would fail lint. I'm getting the following message when I do that:

```
Cannot assign to 'postRes' because it is a read-only property.                                                                                                                         131       this.state.postRes = Some(this.isoData.routeData[0] as GetPostResponse);
```

**Comment by Havunen** [comment] 2022-08-02 14:34
ah yes, I will fix that

**Comment by Havunen** [comment] 2022-08-02 18:26
inferno 8.0.2 should allow setting properties directly to state https://github.com/infernojs/inferno/commit/d0ccb387a8073c4205264e0a41f59189885f30c1

**Comment by dessalines** [comment] 2022-08-02 18:34
This is still an issue when using closures in the constructor. For example, try : 

`setTimeout(() => this.state.counter = 0, 10);`

in the constructor.

**Comment by dessalines** [comment] 2022-08-02 19:13
Just posting this because you might find it useful, but I have to use closures because I recently converted all typescript style optionals ( IE `?` ) , to rust-style `Option` and `Result` using this library: https://github.com/sniptt-official/monads . Then you can handle the nonexistent cases really easily with `match`:

```ts
myOptional.match({
  some: val => // Do something
  none: // Do something else
});
```

It eliminated a whole class of NullPointerException type bugs, and was really useful especially for API-type libraries.

**Comment by dessalines** [comment] 2022-08-02 19:25
Another thing: would it be possible to have a lint that dissallows using setState in the constructor? Otherwise these bugs become runtime errors rather than compile-time ones.

If not, or if that should be a different issue, that's no problem.

**Comment by Havunen** [comment] 2022-08-02 19:28
Yeah, thats good idea. Can you create a new issue please 👍

**Comment by Havunen** [comment] 2022-08-18 16:09
> If I use state = ... in a constructor, it fails lint

What linting rule is that? I think my previous fix should be reverted, I somehow thought readonly made that, but of course readonly property can be set in constructor

**Comment by dessalines** [comment] 2022-08-19 17:47
This one: https://github.com/infernojs/eslint-plugin-inferno/blob/master/docs/rules/no-direct-mutation-state.md

And it seems to only be violated if I use it in a closure in the constructor.

**Comment by Havunen** [comment] 2022-08-19 19:01
Ah, just normal closure in constructor? That sounds like a bug in the eslint rule. Can you post a small code example just to be sure! Thanks!

**Comment by Havunen** [comment] 2022-08-30 05:29
Yes the linting error is correct, it fails because its bad practice to assign value to state. If value is directly assigned to state it does not cause re-render like `setState` does to make sure the rendered html is up to date. If the value is something you do not want to keep in state then you could use class fields for storing it. If the value indeed should be in the state, then you should refactor the code to call `this.setState({counter: 0});`. But that's also not good option, because when using state its good practice to initialize the state variable immediately by assigning initial state value to the state. Calling `setState` method in the constructor also has issue that if the function callback gets executed before class instance is created, it cannot re-render and then it causes this error:

```
404: Error: Inferno Error: cannot update state via setState() in constructor. Instead, assign to this.state directly or define a state = {};
```

You have 2 choices here: Initialize state variable by setting the value in the constructor and use `setState` logic in "componentWillMount", or if you know this is not an problem for you, you can disable the linting rule.

See: https://github.com/infernojs/eslint-plugin-inferno/blob/master/docs/rules/no-direct-mutation-state.md

**Closed by Havunen** 2022-08-30 05:29 UTC
Labels: question

**Comment by dessalines** [comment] 2022-09-02 14:59
> If the value indeed should be in the state, then you should refactor the code to call this.setState({counter: 0});

If you use `setState` in a constructor, inferno will give you the following error:

> 404: Error: Inferno Error: cannot update state via setState() in constructor. Instead, assign to this.state directly or define a state = {};

**Comment by Havunen** [comment] 2022-09-02 15:04
Yeah don't do that, instead call setState in componentWillMount

**Comment by dessalines** [comment] 2022-09-02 15:16
Would you say its a better practice then to move all state-related initial setting from the constructor to componentWillMount?

**Comment by Havunen** [comment] 2022-09-02 17:13
Initialize the state in constructor with default values, don't do async code there, because then its not really initializing anything. ( like setTimeout). And when you do asynchronous code like network requests do them in componentWillMount or componentDidMount and use setState to set value to state
